language: elixir

elixir:
  - 1.2
  - 1.3
  - 1.3.4

otp_release:
  - 18.0
  - 19.1
  - 19.2

matrix:
  exclude:
  - elixir: 1.2
    otp_release: 19.1
  - elixir: 1.2
    otp_release: 19.2

script:
  - MIX_ENV=coverage mix test --cover

branches:
  only:
    - master
