language: elixir

elixir:
  - 1.3
  - 1.3.4
  - 1.4.0

otp_release:
  - 18.0
  - 19.1
  - 19.2

matrix:
  exclude:
  - elixir: 1.3
    otp_release: 19.2
  - elixir: 1.3.4
    otp_release: 19.1
  - elixir: 1.4.0
    otp_release: 18.0

script:
  - mix deps.get && MIX_ENV=test mix deps.compile backoff && ./integration/hack_out_incompatible_tests.sh && mix test --cover

branches:
  only:
    - master
